version: "3"
services:
  app:
    image: docker.pkg.github.com/whockey/drill-sergeant/drill-sergeant:latest
    ports:
      - 8081:8080
    depends_on:
      - redis
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  redis-data:
